### ISSUE TITLE
Can we know on user's phone have or not have map application?

### ISSUE THREAD

**Issue by vinhtran6921** [tschoffelen/react-native-map-link#107]
How can I implement like this image. Can we get info app on user's phone?.
On Popup component, it only show app that installed on phone. How I can get info like this on my component?
![image](https://user-images.githubusercontent.com/53859772/64775385-3ef0a800-d580-11e9-9e55-9c0dc94292f6.png)
![image](https://user-images.githubusercontent.com/53859772/64775577-ad356a80-d580-11e9-9fb1-54ab707ff4bf.png)

**Comment by tschoffelen** [comment]
Hi, to do that, you'd need to use the internal function [`getAvailableApps`](https://github.com/tschoffelen/react-native-map-link/blob/master/src/utils.js#L12) and build your own popup.

This is not part of the scope of this library.
