### ISSUE TITLE
Unnamed location

### ISSUE THREAD

**Issue by wiliander** [tschoffelen/react-native-map-link#108]
Hi, is there a way to send the name of the address or a title so it won't appear on my map, "unnamed location"?

this is due to googleForceLatLon: true

<img width="356" alt="Captura de Tela 2019-09-20 às 15 26 50" src="https://user-images.githubusercontent.com/39866928/65350494-39b4de00-dbbc-11e9-9f58-7b4c4851b280.png">

**Comment by mixcas** [comment]
@wiliander how did you solve this?

**Comment by tschoffelen** [comment]
Doesn't the `title` parameter solve that?
