### ISSUE TITLE
When browser version of Google Maps is accessed from iOS, the pointer for the given location's coordinates is not shown

### ISSUE THREAD

**Issue by 20SangHun00** [tschoffelen/react-native-map-link#109]
I'm trying to implement this module in my app, and have an issue related to the browser version of Google Maps. I've given the possibility to access multiple map apps (for now Apple map, and Google Maps), and when I choose from the menu the Google Maps, as expected it redirects me to the browser version of the Google, if the phone doesn't have Google Maps installed, and here appears the problem, the marker is not set on the location which I'm setting from my app, and moreover, it doesn't even want to build the path if I give and the startLocation's coordinates. In the Apple maps everything is going great

Here's a snippet of my code:

```
gMaps = async () => {
    const {startLocation} = this.state;
    const {lat, lon} = this.state.item.location; //lat & lon come as strings

    showLocation({
      latitude: parseFloat(lat),
      longitude: parseFloat(lon),
      sourceLatitude: startLocation.latitude,
      sourceLongitude: startLocation.longitude,
      title: 'Pickup Location', 
      googleForceLatLon: true, 
      alwaysIncludeGoogle: true, 
      dialogTitle: 'This is the dialog Title', 
      dialogMessage: 'This is the amazing dialog Message',
      cancelText: 'This is the cancel button text', 
      appsWhiteList: ['google-maps', 'apple-maps'],
    });
  };
```

**Comment by 20SangHun00** [comment]
I fount the problem. When redirecting to the browser version, the app sends a link similar to this one `https://www.google.com/maps?q=LAT2,LON2&api=1&saddr=LAT1,LON1&daddr=LAT2,LON2` (change LAT1, LAT2, LON1 & LON2 with yours coordinates), but now, google changed the structure of this link to this `https://www.google.com/maps/dir/'LAT1,LON1'/'LAT2,LON2'` , what can be done for resolving the problem?

**Comment by 20SangHun00** [comment]
Here's the structure of the links which redirects you to the directions from point A to point B and to the one which sets a pointer to the given place.

> : Direction from a place to another 

`https://www.google.com/maps/dir/'LAT1,LON1'/'LAT2,LON2'`

> : Pointer to a desired location

`https://www.google.com/maps/place/'LAT1,LON1'`

**Comment by tschoffelen** [comment]
Feel free to submit a PR for this.

One thing to note: the HTTP link is also used by Android to open the Google Maps app, so we need to check if opening Google Maps on Android still works as expected with this new URL structure.

**Comment by 20SangHun00** [comment]
If it is of any help, I've sent a link similar to this in messenger to myself, and accessed it from both iOS and Android, and it opened without any problems, though it was opened in messenger's in-app browser

**Comment by 20SangHun00** [comment]
> Feel free to submit a PR for this.
> 
> One thing to note: the HTTP link is also used by Android to open the Google Maps app, so we need to check if opening Google Maps on Android still works as expected with this new URL structure.

I can make that pull request, but I didn't changed the scenario for placeID and encodedTitle, as I do not know how to work with them.

**Comment by 20SangHun00** [comment]
Ok, PR done

**Comment by arnaudambro** [comment]
Hi there,

Maybe I missed something, but I have the v2.5.2 installed and the google maps link still sends to something like 
https://www.google.com/maps?q=49.81458,0.58729&api=1&saddr=49.81345,0.51375&daddr=49.81458,0.58729, on iOS 13.1
