### ISSUE TITLE
Cannot pass address as a string to show location on map

### ISSUE THREAD

**Issue by vishgoel007** [tschoffelen/react-native-map-link#111]
If i have address as a string. Can i use that library to show location of the same address?

**Comment by vishgoel007** [comment]
@tschoffelen Can you please give me some suggestion regarding this issue?

**Comment by tschoffelen** [comment]
You’d first have to geocode the address into a lat,lng pair to be use it with this library. There’s other libraries and APIs you can utilise to do this.
