### ISSUE TITLE
[suggestion ] Add locale for constants

### ISSUE THREAD

**Issue by mustafaskyer** [tschoffelen/react-native-map-link#120]
hey @tschoffelen 
thanks for your great work,  Appreciated :)
I suggest to add locale for constants, for other langs support,
or just user can pass string, which should override the default one
regards

**Comment by tschoffelen** [comment]
Hi, thanks!

It's already possible to [override](https://github.com/tschoffelen/react-native-map-link#usage) most of the strings in the library, except for the app names themselves.

Feel free to submit a PR if you need this feature.

**Comment by tschoffelen** [comment]
Ability to set custom app titles is now possible thanks to @exiam (#120). Are you okay with me closing this issue, or is there still something missing when it comes to localization/translation capabilities?
