### ISSUE TITLE
Waze navigation and note in README.md

### ISSUE THREAD

**Issue by grifotv** [tschoffelen/react-native-map-link#123]
Waze navigation worked for me in iOS. I'm wondering if the note in the README.md `Currently supports all apps except Waze.` is not relevant anymore and could be removed.

**Comment by tschoffelen** [comment]
Hi! I think navigation works, but not from a specific source lat/lng. It will default to your current location, I presume.

Looking at the code, the source lat/lng is not passed along to Waze: https://github.com/tschoffelen/react-native-map-link/blob/master/src/index.js#L128-L131

**Comment by grifotv** [comment]
I see now. I'm my case I didn't notice this difference as the source lat/lng was my current location.

Thanks for clarifying!
