### ISSUE TITLE
Opening google maps in safari does not generate the url nor url parameters correctly

### ISSUE THREAD

**Issue by cenzovit** [tschoffelen/react-native-map-link#124]
The url opened in safari when forcing google maps (alwaysIncludeGoogle set to true) on iOS when app isn't downloaded is not generated correctly. Not sure if google changed their url / parameters, but see the following for what seems to be an up-to-date reference: https://developers.google.com/maps/documentation/urls/guide#search-action

**Comment by tschoffelen** [comment]
Hey, thanks for reporting! Feel free to submit a PR, and I'll gladly merge it.
