### ISSUE TITLE
Waze option not showing

### ISSUE THREAD

**Issue by ebnersilva** [tschoffelen/react-native-map-link#131]
I was using until a while ago and everything worked perfectly, but now, for some reason, the option of navigation by the waze app is not shown.

**Comment by tschoffelen** [comment]
Hi!

Is this on iOS or Android?

**Comment by ebnersilva** [comment]
Hi!
I took the test on android

**Comment by lpikora** [comment]
This library using Alert (https://reactnative.dev/docs/alert) to show app options on Android.

https://github.com/tschoffelen/react-native-map-link/blob/625c3eac82c203a95ad24d20288f183bf07cdb71/src/utils.js#L129

**But on Android at most three buttons can be specified**. So it only shows two options at most (see React Native docs). I don't know if this is intended.

You can use Popup instead... https://github.com/tschoffelen/react-native-map-link/blob/master/docs/popup.md

**Comment by ebnersilva** [comment]
@lpikora oh great! Your solution works like magic!

Thanks! 👍
