### ISSUE TITLE
Alert not cancelable on back

### ISSUE THREAD

**Issue by QRCharlie** [tschoffelen/react-native-map-link#135]
On Android the back button does not dismiss the alert.

As per documentation https://reactnative.dev/docs/alert options may include boolean cancelable.

Option cancelable seems to be missing in https://github.com/tschoffelen/react-native-map-link/blob/master/src/utils.js at line 129.

**Comment by tschoffelen** [comment]
Good catch? Would you mind opening a PR to add this?

**Comment by QRCharlie** [comment]
K, will do.
