### ISSUE TITLE
New platforms 

### ISSUE THREAD

**Issue by Luisquii** [tschoffelen/react-native-map-link#140]
Hi, just a simple question.

Are you planning or is it possible to add Didi and Cabify to this repo?

**Comment by tschoffelen** [comment]
Hi! Good question. Yes, there are people opening PRs for support for new platforms all the time, and I happily accept those.

I don't have time to build those integrations myself, but there is a guide on how to do it here: https://github.com/tschoffelen/react-native-map-link/blob/master/docs/add-app.md
