### ISSUE TITLE
Open default map with specific navigation method

### ISSUE THREAD

**Issue by rheng001** [tschoffelen/react-native-map-link#20]
Hi, is it possible to add another param to the showLocation function to customize the navigation method when we open the app? For example, when I enter a source and destination I also want the option to specify the navigation method as walking **initially** or driving/cycling for google maps. 

Thanks!

**Comment by tschoffelen** [comment]
Definitely possible to add that I think, at least I guess apps like Google Maps will probably support that. Unfortunately I don’t have time to add it myself, but I would definitely accept a Pull Request that implements that functionality.
