### ISSUE TITLE
Uber title not encoded when in display

### ISSUE THREAD

**Issue by cblaze22** [tschoffelen/react-native-map-link#268]
When sending a title to Uber it is displayed as not encoded.  Is there something we can do to fix that? Google, Apple and Waze work just fine.

```
const result = await getApps({
        latitude: data?.data?.dirs?.lat,
        longitude: data?.data?.dirs?.lng,
        title: data?.t,
        googleForceLatLon: true,
        alwaysIncludeGoogle: true,
      });
```

![1BE80430-2CBB-4DC5-A80E-13C08396A7B4](https://github.com/includable/react-native-map-link/assets/556494/1c5b5e56-0e97-4020-8c66-730ec60e7f50)

**Comment by tschoffelen** [comment]
We might have to encode this differently, for example by using `+` instead of `%20`, or maybe it likes just no encoding whatsoever. I'm not able to give this a try at the moment, but happy to accept a PR to fix this.

**Comment by cblaze22** [comment]
Should be easy fix
