### ISSUE TITLE
Using showLocaiton links straight to maps

### ISSUE THREAD

**Issue by szarbartosz** [tschoffelen/react-native-map-link#298]
Using `react-native-map-link` with `expo`  in the following way:
```
export const linkToMaps = async (latitude: number, longitude: number, label: string) => {
  await showLocation({
    latitude: latitude,
    longitude: longitude,
    title: label,
    dialogTitle: t('openInMaps'),
    dialogMessage: t('whichAppToUse'),
    cancelText: t('cancel'),
  });
};
```
The function is triggered by a button click - when tried it via `expo-go` on an Android device the modal with alternative map apps was presented - when doing so on the iOS simulator or iOS device via `expo-go`, there is an immediate link to the iOS maps without presentation of the alternatives. (I added the `react-native-map-link` plugin to the `app.json`)

**Comment by SzymonGonet** [comment]
+1 @tschoffelen

**Comment by tschoffelen** [comment]
When using Expo Go, only certain URL schemes will be whitelisted, regardless of whether the plugin is added or not. 

If that leaves only one available maps option that can be detected, it will open that app directly. A native build on your app (e.g. not using Expo Go) on a device with more than one of the supported apps installed should show a menu with options.

**Comment by mattHollywood87** [comment]
You can also force it to show google maps as an option in expo go using the alwaysIncludeGoogle flag.

**Comment by szarbartosz** [comment]
Thank you for the response @tschoffelen @mattHollywood87 - closing as complete 🙌
