### ISSUE TITLE
search by "title" not working when lat and long equal zero or null

### ISSUE THREAD

**Issue by LuongTruong** [tschoffelen/react-native-map-link#303]
I am using the below code:

```
showLocation({
  latitude: props.lat,
  longitude: props.lng,
  title: props.title,

  // I comment out this field to make sure we search by "title"
  // googleForceLatLon: false, // optionally force GoogleMaps to use the latlon for the query instead of the title
});

```

Expectation
===

if "props.lat" and "props.lng" equal zero or null, we still move to Google maps and search by "title".

Actual
===

if "props.lat" and "props.lng" equal zero or null, we can't move to Google maps

Work around
===

I use the below code as a work around

```
showLocation({
  address: props.address,
  dialogTitle: 'Open in Maps',
  dialogMessage: 'Please select your favorite Maps',
  alwaysIncludeGoogle: true,
  appsWhiteList: ['google-maps', 'apple-maps'],
}).then();
```

Hope this issue report can help you guys somehow. Thank you for the great library!

**Comment by tschoffelen** [comment]
Hi there!

This is possible, but it requires specifying the `address` parameter instead, as it has a different purpose to the `title` parameter. Please see the second example in [this section](https://github.com/tschoffelen/react-native-map-link#full-usage) of the README.

```js
import {showLocation} from 'react-native-map-link';

showLocation({
  address: '1600 Pennsylvania Avenue NW, Washington, DC 20500'
});
```

**Comment by LuongTruong** [comment]
Hello @tschoffelen , thank you for the suggestion. I try the address and it is working now. Below is the code I am using. Hope it can help people who have the same issue as me in the future

For Android
```
showLocation({
  address: props.address,

  dialogTitle: 'Open in Maps',
  dialogMessage: 'Please select your favorite Maps',
  alwaysIncludeGoogle: true,
  appsWhiteList: ['google-maps', 'apple-maps'],
}).then();
```

For iOS:
```
showLocation({
  latitude: props.lat || 1,
  longitude: props.lng || 1,
  title: props.address,
  appleIgnoreLatLon: props.lat === 0 || props.lng === 0,

  dialogTitle: 'Open in Maps',
  dialogMessage: 'Please select your favorite Maps',
  alwaysIncludeGoogle: true,
  appsWhiteList: ['google-maps', 'apple-maps'],
}).then();
```
