### ISSUE TITLE
Override application titles

### ISSUE THREAD

**Issue by nicholasc** [tschoffelen/react-native-map-link#48]
Currently, the application titles in the app selection menu are displayed are based on constants. It would be nice if we could override those. For example, using internationalization we could have the apps name translated.

I am suggesting something along the lines of:
```js
const app = await showLocation({
  appTitles: [
    'apple-maps': 'Plans',
    'google-maps': 'Cartes Google',
  ]
});
```

Then this config could be merged with the title constant to generate the menu.

If this is something we want as a new feature, I am willing to implement it and open a PR.

Let me know.

**Comment by tschoffelen** [comment]
Sorry for the late reply!

I personally don't see much use in this for my own apps, but it also wouldn't add too much complexity to the library, so feel free to add it! I'll gladly accept a PR that implements this functionality.
