### ISSUE TITLE
Add support for Careem

### ISSUE THREAD

**Issue by ismaelrumzan** [tschoffelen/react-native-map-link#54]
Are the only apps that will open the ones listed on the readme page?
For example, I don't see "careem" listed - could I find the right id for careem and add it?

**Comment by tschoffelen** [comment]
@ismaelrumzan Yes please! I've created a quick document to outline the steps involved in adding support for a new app to the library: 

https://github.com/includable/react-native-map-link/blob/master/docs/add-app.md

**Comment by ismaelrumzan** [comment]
Thanks for that
I've been trying to figure out what the url scheme would be.
I was able to find the manifest.plist file from the backup and looked the the CFBundleIdentifier
However, these are different from what you've used as URL schemes
For example, google maps is com.google.Maps and you use comgooglemaps://
Is it basically the same but all lowercase and without dots?
But Uber is com.ubercab.UberClient and you have uber://

**Comment by tschoffelen** [comment]
`CFBundleIdentifier` is not the URL scheme. There should be one or more keys called `CFBundleURLSchemes` which will contain the URL scheme:

Example:

```xml
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleURLName</key>
		<string>nl.hoyapp.hoyapp</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>hoyapp</string>
		</array>
	</dict>
</array>
```

In this example the URL scheme is `hoyapp://`.

**Comment by ismaelrumzan** [comment]
Thanks for that, I'm need to download the ipa to find that data
I got google maps to load now - however, the co-ordinates are not being passed when I click on it.
It works fine for uber and apple maps. In google maps, it seems to try to search on the name passed.
Any ideas?

**Comment by tschoffelen** [comment]
Just the IPA won't be enough, because you need to know the rest of the URL scheme (how the parameters work) as well. 

They do seem to have [online documentation](https://developer.careem.com/) (click Deep Linking top right), but the Developer portal requires signing in, and the Sign Up form doesn't seem to work, like [these people also found out](https://github.com/dpa99c/phonegap-launch-navigator/issues/204).

**Comment by ismaelrumzan** [comment]
Great, I found the url scheme and added all the info in a forked version of your source code.
How can I test it with the new source and make sure things work on both android and ios, without requesting a pull request to push back to your code?

**Comment by ismaelrumzan** [comment]
Thanks,
Got it to work - it opens the careem app - now I need to troubleshoot how to pass the co-ordinates - any tips on finding this or are there a set of "limited" conventions?

**Comment by tschoffelen** [comment]
Not really, it's might be similar to the way the Uber deep linking works, but you would really need the documentation I linked to in a previous comment to know for sure.

I've already been looking around if I could find any other resources for Careem, but I couldn't find any...

**Comment by ismaelrumzan** [comment]
Hey, I registered with Careem but have not got access yet. Question about setting the appwhitelist inside the app using the popup. I did it but it does not pick it up - any suggestions?

**Comment by baselbj** [comment]
Hi, any updates on this?

**Comment by tschoffelen** [comment]
Still waiting for someone to find out info about their URL scheme. I've tried signing up for their developer portal multiple times, but it don't seem to work.

As soon as we have the URL scheme data it should be really simple to build the actual integration.

**Comment by baselbj** [comment]
thank you I'll also try to register and help

**Comment by tschoffelen** [comment]
Hi @baselbj have you been able to access Careem's developer docs? Otherwise I might close this issue for now.

**Comment by baselbj** [comment]
to tell you the truth I totally forgot about this ... I will start working on that now... sorry for that

**Comment by baselbj** [comment]
after some tries and playing with my Careem accounts I registered a developer account the response is:

> You are almost there!
> We have received your request to become a developer. A Careem representative will get in touch with you shortly. 

waiting for there response

**Comment by tschoffelen** [comment]
I think I also got to that point, and then never got a response :)

We'll see, thanks for your quick reply though!

**Comment by baselbj** [comment]
I will keep trying to contact them and trying to find some one that can help the information needed is the CFBundleURLSchemes , right?

**Comment by tschoffelen** [comment]
Yep, just some documentation on how their URL scheme works, like this from Uber: https://developer.uber.com/docs/riders/ride-requests/tutorials/deep-links/introduction

**Comment by tschoffelen** [comment]
Closing this for now until we have documentation for Careem.

**Comment by baselbj** [comment]
sorry for that I will find some way to contact them ... I will try contacting their branch in Jordan ... Hopping to remember doing this
