### ISSUE TITLE
No apps shown

### ISSUE THREAD

**Issue by vladromila** [tschoffelen/react-native-map-link#89]
Hi guys. I ejected an expo project to react-native and the popup doesn't work anymore. I upgraded to @2.4.3 but it didn't fix it for me. I must say that on expo, in order to make it work, i needed to add permission READ_PHONE_STATE. I added this to Manifest but it still doesn't work :
`<uses-permission android:name="android.permission.READ_PHONE_STATE"/>`
Any ideas? Thanks in advance

**Comment by hayanisaid** [comment]
The same!

**Comment by gde-adi** [comment]
Have you try version 2.1.1 ? I think that this version is better than other version and also more stable.

Just suggestion. :)

**Comment by tschoffelen** [comment]
We've just released a new version `v2.5.1`, could you give that a try?

**Comment by tschoffelen** [comment]
Closing this now, as I believe this has been fixed from my own tests and the experiences of other users. Please open a new ticket if you still experience problems with the latest version.
